name: First Workflow
on: 
    push:
        branches: develop
jobs:
    trending_movies:
        runs-on: ubuntu-latest
        env:
            tmdb_apikey: ${{ secrets.TMDB_APIKEY }}
            tmdb_url_trending: 'https://api.themoviedb.org/3/trending/movie/week'
        steps:
            - name: Get trending movies
              run: curl -s --url $tmdb_url_trending?api_key=$tmdb_apikey