name: First Workflow
on: 
    push:
        branches: develop
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Say something
              run: |
                echo "A little less conversation"
                echo "A little more action"